team:
   name: Tupperware
   members:
      - user: s.salazarc@uniandes.edu.co
        percentage: 25
      - user: h.galindos@uniandes.edu.co
        percentage: 25
      - user: jf.guzmanc1@uniandes.edu.co
        percentage: 25
      - user: jm.carrillo@uniandes.edu.co
        percentage: 25
board: N/A
user-management:
  folder: users
  port: 3000
  authors:
    - h.galindos@uniandes.edu.co
post-management:
  folder: posts
  port: 3001
  authors:
    - jm.carrillo@uniandes.edu.co
offer-management:
  folder: offers
  port: 3003
  authors:
    - s.salazarc@uniandes.edu.co
route-management:
  folder: routes
  port: 3002
  authors:
    - jf.guzmanc1@uniandes.edu.co