team:
   name: Tupperware
   members:
      - user: s.salazarc@uniandes.edu.co
        percentage: 25
      - user: h.galindos@uniandes.edu.co
        percentage: 25
      - user: jf.guzmanc1@uniandes.edu.co
        percentage: 25
      - user: jm.carrillo@uniandes.edu.co
        percentage: 25
board: N/A
url: 35.244.174.147
user-management:
  folder: users
  authors:
    - h.galindos@uniandes.edu.co/jf.guzmanc1@uniandes.edu.co
sendmail-management:
  folder: function-sendmail
  authors:
    - jf.guzmanc1@uniandes.edu.co
rf006-management:
  folder: rf006
  authors:
    - s.salazarc@uniandes.edu.co/jm.carrillo@uniandes.edu.co
rf006-poll-management:
  folder: rf006_poll
  authors:
    - s.salazarc@uniandes.edu.co/jm.carrillo@uniandes.edu.co
