version: "3.2"
services:
  user_db:    
    image: postgres:14.1-alpine
    container_name: user_db
    env_file: ./users/.env.database   
  offers_db:    
    image: postgres:14.1-alpine
    container_name: offers_db
    env_file: ./offers/.env.database   
    restart: always
    ports:
      - "5432:5432"    
    networks:
      - user_net
  
  mcs_users:
    restart: always
    image: mcs_users:latest
    env_file: ./users/.env.development      
    build: 
      context: ./users
      dockerfile: Dockerfile
      target: dev
      # target: prod      
    container_name: mcs_users
    ports:
      - "3000:5000"
    networks:
      - user_net
      - app_net      
    depends_on:
      - user_db
      - offer_net
  
  mcs_offers:
    restart: always
    image: mcs_offers:latest
    env_file: ./offers/.env.development      
    build: 
      context: ./offers
      dockerfile: Dockerfile
      target: dev
      # target: prod      
    container_name: mcs_offers
    ports:
      - "3003:5000"
    networks:
      - offer_net
      - app_net      
    depends_on:
      - offers_db

networks:
  app_net:
    driver: bridge
  user_net:
    driver: bridge
  offer_net:
    driver: bridge