version: '3'
services:
  scores_db:
    container_name: scores_db
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PgNube202314
    restart: always
    networks:
      - app_net   
  
  scores:
    container_name: scores
    build: 
      context: ./scores
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    environment:
      DB_NAME: postgres
      DB_HOST: scores_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: PgNube202314
    restart: always
    networks:
      - app_net
    depends_on:
      - scores_db
  
networks:
  app_net:
    driver: bridge