version: "3.2"
services:
  postgresql_user_db:    
    image: postgres:latest
    container_name: postgresql_user_db
    env_file: ./users/.env.database   
    restart: always
    ports:
      - "5432:5432"
    networks:
      - user_net    
  
  mcs_users:
    restart: always
    image: mcs_users:latest
    env_file: ./users/.env.development      
    command:
      - /bin/bash
      - -c
      - |
        cd /backend/src
        sh run_commands.sh
    volumes:
      - ./users/:/backend/
    build: ./users
    working_dir: /backend/
    container_name: mcs_users
    ports:
      - "5000:5000"
    networks:
      - user_net
      - app_net      
    depends_on:
      - postgresql_user_db
  
networks:
  app_net:
    driver: bridge
  user_net:
    driver: bridge