version: '3'
services:
  users_db:
    container_name: users_db
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always
    networks:
      - user_net   
  
  users:
    container_name: users
    build: 
      context: ./users
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    environment:
      DB_NAME: usersdb
      DB_HOST: users_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
    restart: always
    networks:
      - user_net 
      - app_net
    depends_on:
      - users_db
  
  posts_db:
    container_name: posts_db  
    image: postgres:14.1-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always
    networks:
      - post_net

  posts:
    container_name: posts
    build: 
      context: ./posts
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3001:3000"
    environment:
      DB_NAME: postsdb
      DB_HOST: posts_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      USERS_PATH: "http://users:3000"
    restart: always
    networks:
      - post_net 
      - app_net
    depends_on:
      - posts_db
      - users 

  routes_db:    
    container_name: routes_db
    image: postgres:14.1-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: routesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin  
    restart: always
    networks:
      - route_net
  
  routes:
    container_name: routes
    build: 
      context: ./routes
      dockerfile: Dockerfile
      target: prod     
    environment:
      DB_NAME: routesdb
      DB_HOST: routes_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      USERS_PATH: "http://users:3000"
    ports:
      - "3002:3000"
    restart: always      
    networks:
      - route_net
      - app_net      
    depends_on:
      - routes_db
      - users       
  
  offers_db:
    container_name: offers_db  
    image: postgres:14.1-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: offersdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always
    networks:
      - offer_net 

  offers:
    container_name: offers
    build: 
      context: ./offers
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3003:3000"
    environment:
      DB_NAME: offersdb
      DB_HOST: offers_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      USERS_PATH: "http://users:3000"
    restart: always
    networks:
      - offer_net
      - app_net
    depends_on:
      - offers_db
      - users

networks:
  app_net:
    driver: bridge
  user_net:
    driver: bridge
  offer_net:
    driver: bridge
  route_net:
    driver: bridge    
  post_net:
    driver: bridge