###################################
# INGRESS
###################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress-grupo8-k8s
  labels:
    name: gateway-ingress-grupo8-k8s
spec:
  rules:
  - http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: users-service
            port: 
              number: 80
      - path: /credit-cards
        pathType: Prefix
        backend:
          service:
            name: rf006-service
            port: 
              number: 80
      - path: /poll
        pathType: Prefix
        backend:
          service:
            name: rf006-poll-service
            port: 
              number: 80
      - path: /native
        pathType: Prefix
        backend:
          service:
            name: truenative-service
            port: 
              number: 80      