apiVersion: v1
stringData:
  DB_NAME : "postgres"
  DB_HOST : "192.168.0.7"
  DB_PORT : "5432"
  DB_USER : "postgres"
  DB_PASSWORD : "PgNube202314"
  USERS_PATH : "http://users-service"
  ROUTES_PATH : "http://routes:3000"
  OFFERS_PATH : "http://offers:3000"
  POSTS_PATH : "http://posts:3000"
  SCORES_PATH : "http://scores:3000"  
kind: Secret
metadata:
  name: appsecrets