name: Test coverage
on:
  push:
    branches: 
      - main
jobs:
  Test_Coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]
    steps:
      - uses: actions/checkout@v1
      - name: Create the Test DB
        working-directory: ./users
        run: docker run -d -p 5432:5432 --name userdb -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=admin -e POSTGRES_DB=userdb postgres:14.1
      - name: Install pipenv for users mcs
        working-directory: ./users
        run: pip install pipenv
      - name: Install dependencies for users mcs
        working-directory: ./users
        run: pipenv install --system --deploy
      - name: Run unit tests for users mcs
        working-directory: ./users
        run: pytest --cov-fail-under=70 --cov=src
      - name: CleanUp after test part 1
        working-directory: ./users
        run: docker rm -vf $(docker ps -aq) 
      - name: CleanUp after test part 2
        working-directory: ./users
        run: docker rmi -f $(docker images -aq)

